# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/marius/DISK GROS/Projets informatiques/Imolation/Git/Imolation/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(80, 50, 631, 351))
        self.Image.setObjectName("Image")
        self.Resultat = QtWidgets.QLabel(self.centralwidget)
        self.Resultat.setGeometry(QtCore.QRect(250, 440, 131, 71))
        self.Resultat.setObjectName("Resultat")
        self.Droite = QtWidgets.QPushButton(self.centralwidget)
        self.Droite.setGeometry(QtCore.QRect(730, 220, 61, 61))
        self.Droite.setObjectName("Droite")
        self.Gauche = QtWidgets.QPushButton(self.centralwidget)
        self.Gauche.setGeometry(QtCore.QRect(10, 220, 61, 61))
        self.Gauche.setObjectName("Gauche")
        self.Requete = QtWidgets.QLineEdit(self.centralwidget)
        self.Requete.setGeometry(QtCore.QRect(480, 490, 281, 31))
        self.Requete.setObjectName("Requete")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 400, 211, 91))
        self.label.setObjectName("label")
        self.Validation = QtWidgets.QPushButton(self.centralwidget)
        self.Validation.setGeometry(QtCore.QRect(590, 530, 80, 23))
        self.Validation.setObjectName("Validation")
        self.Resultat_2 = QtWidgets.QLabel(self.centralwidget)
        self.Resultat_2.setGeometry(QtCore.QRect(60, 440, 131, 71))
        self.Resultat_2.setObjectName("Resultat_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Image.setText(_translate("MainWindow", "Résultat de requête ici qd t\'auras cherché"))
        self.Resultat.setText(_translate("MainWindow", "Résultat de l\'image"))
        self.Droite.setText(_translate("MainWindow", ">"))
        self.Gauche.setText(_translate("MainWindow", "<"))
        self.label.setText(_translate("MainWindow", "Mets ce que tu cherches ici le 100\n"
" et appuie sur le bouton"))
        self.Validation.setText(_translate("MainWindow", "Validation"))
        self.Resultat_2.setText(_translate("MainWindow", "Résultat de l\'image : "))
